### PR TITLE
implements relational operators

### LINKED ISSUE #13: missing comparison overloads
Do you intend for the tuple header to provide comparison operator overloads?  Or should users just provide them?

I'm about them to implement them and can do a PR.   Now that tie (and related issues with tuples of references interacting with tuples of values), I think that Thrust with the new, non-recursive, variadic tuple should be working once these operators are added.

### PR DESCRIPTION
**Pull request by andrewcorrigan**
This should resolve https://github.com/jaredhoberock/tuple/issues/13

I added a bunch of tests to demo.cpp, but am not sure if they are sufficient or excessive.

### CODE REVIEW

**Comment by andrewcorrigan** [comment]
Should also resolve https://github.com/jaredhoberock/tuple/issues/15, and fixes other minor issues (missing return and enable_if).

With these fixes, Thrust is now working using this non-recursive, variadic tuple implementation.  I'm going to push this new tuple into my Thrust branch tomorrow. It currently takes ~8 GB to compile my code with the original non-variadic thrust::tuple, exceeds 16 GB with the previous variadic tuple.  Hopefully, things will improve with this version.  If not, I'll have to disable a lot of new features in my code when using CUDA, until you guys replace the EDG frontend with Clang :(

**Comment by andrewcorrigan** [comment]
Also resolves https://github.com/jaredhoberock/tuple/issues/16

**Comment by jaredhoberock** [comment]
This PR breaks Agency, so I can't accept it.

It looks like the problem is the `operator=` overloads added by commit 702a056

Why was it necessary to introduce these? I don't think the libcxx implementation has them.

**Comment by andrewcorrigan** [comment]
In short, the following doesn't compile without these overloads:

```
  foo::tuple<int,int,int> b(1,2,3);    
  auto x = foo::tie(b);
  x = x;    
```

Full details are described in https://github.com/jaredhoberock/tuple/issues/15.

**Comment by jaredhoberock** [comment]
This PR breaks `forward_as_tuple`:

```
#include <tuple>
#include <utility>

template<class... Args>
void foo(Args&&... args)
{
  auto args_tuple = std::forward_as_tuple(std::forward<Args>(args)...);
}

int main()
{
  foo(1);
  return 0;
}
```

```
$ clang -std=c++11 -Iinclude test_forward_as_tuple.cpp 
In file included from test_forward_as_tuple.cpp:1:
include/tuple:492:9: error: call to implicitly-deleted copy constructor of 'base_type' (aka '__tuple_base<__tuple_make_index_sequence<sizeof...(Types)>, int &&>')
      : base_{std::move(other.base_)}
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~
test_forward_as_tuple.cpp:7:21: note: in instantiation of member function 'std::tuple<int &&>::tuple' requested here
  auto args_tuple = std::forward_as_tuple(std::forward<Args>(args)...);
                    ^
test_forward_as_tuple.cpp:12:3: note: in instantiation of function template specialization 'foo<int>' requested here
  foo(1);
  ^
include/tuple:257:5: note: copy constructor of '__tuple_base<std::__tuple_index_sequence<0>, int &&>' is implicitly deleted because base class '__tuple_leaf<0UL, int &&>' has a deleted copy constructor
  : public __tuple_leaf<I,Types>...
    ^
include/tuple:228:7: note: copy constructor of '__tuple_leaf<0, int &&>' is implicitly deleted because field 'val_' is of rvalue reference type 'int &&'
    T val_; // XXX apply empty base class optimization to this
      ^
1 error generated.
```

**Comment by andrewcorrigan** [comment]
Looks similar to #15, which my PR fixes, only now with r-value reference overloads being required. 

My guess is that overloads analogous to what I added in https://github.com/jaredhoberock/tuple/commit/702a056aeda318bce8247bd6060027538bc2ec5d are required, as I sketch below.  I cannot try this out immediately, but will asap, if you don't get to it first.  I'm not sure if it needs to be constructor overloads, operator= overloads, or both...

```
    __TUPLE_ANNOTATION
    __tuple_leaf& operator=(__tuple_leaf&& other)
    {
      mutable_get() = std::move(other.mutable_get());
      return *this;
    }
```

and

```
    __TUPLE_ANNOTATION
    __tuple_base& operator=(__tuple_base&& other)
    {
      swallow((mutable_leaf<I>() = std::move(other.template mutable_leaf<I>()))...);
      return *this;
    }
```

**Comment by jaredhoberock** [comment]
Agreed. Could you pull from this branch:

```
https://github.com/jaredhoberock/tuple/tree/forward_as_tuple_fix
```

**Comment by andrewcorrigan** [comment]
Hi Jared,

Sorry for not commenting here, but I merged your branch last week.  It seems like it works fine.  The test you posted seems to compile on my end.  And my code still compiles with variadic-tuple-equipped Thrust.

Is there anything else?

**Comment by jaredhoberock** [comment]
Thanks. I will test your PR against my stuff and merge it assuming there's no problems.

**Comment by jaredhoberock** [comment]
Everything looks good! Thanks for all the hard work Andrew.

**Pull request merged**
